name = "CoordinateSystems"
uuid = "d6291028-476d-4297-b3a8-76c3a4d31e5f"
authors = ["Lilith Emilia Höddinghaus <info@xefli.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
LinearAlgebra = "1.11.0"
MacroTools = "0.5.16"
